apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: xpfg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xpfg
    app.kubernetes.io/part-of: byoc-app-tyaz
  name: xpfg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: xpfg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: xpfg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-ccuw-tenant/byoc-app-tyaz/xpfg@sha256:59e3e027297c618cdbc57f584dca5912cda500f813a2be901910f8c69ac31287
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
