apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: xpfg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xpfg
    app.kubernetes.io/part-of: byoc-app-tyaz
  name: xpfg
spec:
  rules:
  - host: xpfg-byoc-ccuw-tenant.apps.7272a9d84f5ccc4d37e8.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: xpfg
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
